// ==========================================================================
// driftcrypto Bilingual Translations (CN/EN)
// ==========================================================================

export type Locale = 'en' | 'zh';

export const translations = {
  en: {
    // Header
    header: {
      dashboard: 'Dashboard',
      market: 'Market',
      portfolio: 'Portfolio',
      screener: 'Screener',
      aiChat: 'AI Chat',
      nft: 'NFT',
      more: 'More',
      search: 'Search coins, news...',
      signIn: 'Sign In',
      signUp: 'Sign Up',
      notifications: 'Notifications',
      openMenu: 'Open menu',
      navigationMenu: 'Navigation Menu',
      // More dropdown items
      aiAnalysis: 'AI Analysis',
      technicalAnalysis: 'Technical Analysis',
      sentiment: 'Sentiment',
      enhancedPredictions: 'Enhanced Predictions',
      marketAnalysis: 'Market Analysis',
      macroEconomics: 'Macro Economics',
      correlations: 'Correlations',
      microstructure: 'Microstructure',
      trending: 'Trending',
      predictionAccuracy: 'Prediction Accuracy',
      batchAnalysis: 'Batch Analysis',
      signInRequired: 'Sign in required. Please sign in to access all features.',
    },
    // Hero Section
    hero: {
      title1: 'AI Powered',
      title2: 'Cryptocurrency',
      title3: 'Insights',
      subtitle: 'Live cryptocurrency prices, AI-driven news aggregation, and intelligent market analysis',
      totalMarketCap: 'Total Market Cap',
      volume24h: '24h Volume',
      btcDominance: 'BTC Dominance',
      failedToLoad: 'Failed to load market data',
    },
    // Trending Strip
    trending: {
      label: 'Trending',
      failedToLoad: 'Failed to load trending data',
    },
    // Market Table
    market: {
      title: 'Market Overview',
      searchPlaceholder: 'Search coins...',
      rank: '#',
      name: 'Name',
      price: 'Price',
      change24h: '24h Change',
      marketCap: 'Market Cap',
      volume24h: 'Volume (24h)',
      noCoinsFound: 'No coins found matching your search.',
      failedToLoad: 'Failed to load market data. Please try again later.',
      showing: 'Showing',
      of: 'of',
      // Filters
      all: 'All',
      top10: 'Top 10',
      top50: 'Top 50',
      gainers: 'Gainers',
      losers: 'Losers',
    },
    // News Feed
    news: {
      title: 'AI News Feed',
      all: 'All',
      bullish: 'Bullish',
      bearish: 'Bearish',
      neutral: 'Neutral',
      loadMore: 'Load More',
      noNewsFound: 'No news found for this filter.',
      failedToLoad: 'Failed to load news',
      justNow: 'Just now',
      minutesAgo: '{n}m ago',
      hoursAgo: '{n}h ago',
      daysAgo: '{n}d ago',
      openArticle: 'Open original article',
    },
    // Fear & Greed
    fearGreed: {
      title: 'Fear & Greed Index',
      extremeFear: 'Extreme Fear',
      fear: 'Fear',
      neutralLabel: 'Neutral',
      greed: 'Greed',
      extremeGreed: 'Extreme Greed',
      updated: 'Updated',
      failedToLoad: 'Failed to load data',
    },
    // AI Digest
    digest: {
      title: 'Piaoshu Commentary',
      subtitle: 'AI Daily Digest',
      generatedByAI: 'Generated by AI',
      failedToLoad: 'Failed to load digest',
    },
    // AI Chat
    aiChat: {
      title: 'AI Chat',
      subtitle: 'Ask anything about crypto',
      placeholder: 'Ask about crypto markets, prices, news...',
      send: 'Send',
      thinking: 'Thinking...',
      welcomeMessage: 'Hello! I\'m DriftCrypto assistant. Ask me anything about cryptocurrency markets, prices, news, or technical analysis.',
    },
    // Footer
    footer: {
      disclaimerTitle: 'Investment Disclaimer',
      disclaimer: 'Content available on this site is for informational and educational purposes only. Not to be construed as investment or financial advice. Our site or organization is NOT to be held liable for profit or loss gained from any investments or transactions. Please conduct your own research and consult with qualified financial advisors before making any investment decisions.',
      apiDocs: 'API Docs',
      copyright: '© 2026 driftcrypto.fun. All rights reserved.',
    },
    // Common
    common: {
      loading: 'Loading...',
      error: 'Error',
      retry: 'Retry',
      language: 'Language',
      english: 'English',
      chinese: '中文',
    },
  },

  zh: {
    // Header
    header: {
      dashboard: '仪表盘',
      market: '行情',
      portfolio: '投资组合',
      screener: '筛选器',
      aiChat: 'AI 聊天',
      nft: 'NFT',
      more: '更多',
      search: '搜索币种、新闻...',
      signIn: '登录',
      signUp: '注册',
      notifications: '通知',
      openMenu: '打开菜单',
      navigationMenu: '导航菜单',
      // More dropdown items
      aiAnalysis: 'AI 分析',
      technicalAnalysis: '技术分析',
      sentiment: '情绪指标',
      enhancedPredictions: '增强预测',
      marketAnalysis: '市场分析',
      macroEconomics: '宏观经济',
      correlations: '相关性分析',
      microstructure: '微观结构',
      trending: '热门趋势',
      predictionAccuracy: '预测准确率',
      batchAnalysis: '批量分析',
      signInRequired: '需要登录。请登录以访问所有功能。',
    },
    // Hero Section
    hero: {
      title1: 'AI 驱动的',
      title2: '加密货币',
      title3: '智能洞察',
      subtitle: '实时加密货币价格、AI 驱动的新闻聚合和智能市场分析',
      totalMarketCap: '总市值',
      volume24h: '24小时交易量',
      btcDominance: 'BTC 占比',
      failedToLoad: '加载市场数据失败',
    },
    // Trending Strip
    trending: {
      label: '热门',
      failedToLoad: '加载热门数据失败',
    },
    // Market Table
    market: {
      title: '市场总览',
      searchPlaceholder: '搜索币种...',
      rank: '#',
      name: '名称',
      price: '价格',
      change24h: '24h涨跌',
      marketCap: '市值',
      volume24h: '成交量(24h)',
      noCoinsFound: '未找到匹配的币种。',
      failedToLoad: '加载市场数据失败，请稍后重试。',
      showing: '显示',
      of: '/',
      // Filters
      all: '全部',
      top10: '前10',
      top50: '前50',
      gainers: '涨幅榜',
      losers: '跌幅榜',
    },
    // News Feed
    news: {
      title: 'AI 新闻聚合',
      all: '全部',
      bullish: '看涨',
      bearish: '看跌',
      neutral: '中性',
      loadMore: '加载更多',
      noNewsFound: '该筛选条件下暂无新闻。',
      failedToLoad: '加载新闻失败',
      justNow: '刚刚',
      minutesAgo: '{n}分钟前',
      hoursAgo: '{n}小时前',
      daysAgo: '{n}天前',
      openArticle: '打开原文',
    },
    // Fear & Greed
    fearGreed: {
      title: '恐慌贪婪指数',
      extremeFear: '极度恐慌',
      fear: '恐慌',
      neutralLabel: '中性',
      greed: '贪婪',
      extremeGreed: '极度贪婪',
      updated: '更新于',
      failedToLoad: '加载数据失败',
    },
    // AI Digest
    digest: {
      title: '飘叔锐评',
      subtitle: 'AI 每日点评',
      generatedByAI: 'AI 生成',
      failedToLoad: '加载点评失败',
    },
    // AI Chat
    aiChat: {
      title: 'AI 聊天',
      subtitle: '关于加密货币的任何问题',
      placeholder: '询问加密市场、价格、新闻...',
      send: '发送',
      thinking: '思考中...',
      welcomeMessage: '你好！我是 DriftCrypto 助手。你可以问我任何关于加密货币市场、价格、新闻或技术分析的问题。',
    },
    // Footer
    footer: {
      disclaimerTitle: '投资免责声明',
      disclaimer: '本站内容仅供信息参考和教育用途，不应被理解为投资或财务建议。本站或组织对任何投资或交易产生的利润或损失不承担任何责任。请在做出任何投资决定前自行研究并咨询合格的财务顾问。',
      apiDocs: 'API 文档',
      copyright: '© 2026 driftcrypto.fun. 保留所有权利。',
    },
    // Common
    common: {
      loading: '加载中...',
      error: '错误',
      retry: '重试',
      language: '语言',
      english: 'English',
      chinese: '中文',
    },
  },
} as const;

export type TranslationKey = keyof typeof translations.en;
