'use client';

import { useQuery } from '@tanstack/react-query';
import { Bot, Sparkles } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Skeleton } from '@/components/ui/skeleton';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface AIDigestData {
  digest: string;
  generatedAt: string;
  newsCount: number;
  sources: Array<{ title: string; url: string; snippet: string }>;
}

// ---------------------------------------------------------------------------
// Fetch
// ---------------------------------------------------------------------------

async function fetchAIDigest(): Promise<AIDigestData> {
  const res = await fetch('/api/ai/digest');
  if (!res.ok) throw new Error('Failed to fetch');
  return res.json();
}

// ---------------------------------------------------------------------------
// Simple markdown-like renderer
// ---------------------------------------------------------------------------

function renderDigest(text: string) {
  const lines = text.split('\n');
  const elements: React.ReactNode[] = [];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    // Heading lines (# ...)
    if (line.startsWith('# ')) {
      elements.push(
        <h3
          key={i}
          className="text-sm font-bold text-gold mt-3 mb-1 first:mt-0"
        >
          {line.replace(/^# /, '')}
        </h3>,
      );
      continue;
    }

    // Empty lines become spacers
    if (line.trim() === '') {
      elements.push(<div key={i} className="h-1.5" />);
      continue;
    }

    // Bold + regular text — inline **...** handling
    const parts = line.split(/(\*\*[^*]+\*\*)/g);
    const rendered = parts.map((part, pi) => {
      if (part.startsWith('**') && part.endsWith('**')) {
        return (
          <strong key={pi} className="text-foreground font-semibold">
            {part.slice(2, -2)}
          </strong>
        );
      }
      return <span key={pi}>{part}</span>;
    });

    elements.push(
      <p key={i} className="text-xs text-muted-foreground leading-relaxed">
        {rendered}
      </p>,
    );
  }

  return elements;
}

// ---------------------------------------------------------------------------
// Loading Skeleton
// ---------------------------------------------------------------------------

function DigestSkeleton() {
  return (
    <div className="space-y-2.5 py-1">
      <Skeleton className="h-3.5 w-3/4 rounded" />
      <Skeleton className="h-3 w-full rounded" />
      <Skeleton className="h-3 w-full rounded" />
      <Skeleton className="h-3 w-5/6 rounded" />
      <div className="h-2" />
      <Skeleton className="h-3.5 w-2/3 rounded" />
      <Skeleton className="h-3 w-full rounded" />
      <Skeleton className="h-3 w-4/5 rounded" />
    </div>
  );
}

// ---------------------------------------------------------------------------
// Main Component
// ---------------------------------------------------------------------------

export default function AIDigestSection() {
  const { data, isLoading, isError } = useQuery({
    queryKey: ['ai-digest'],
    queryFn: fetchAIDigest,
    staleTime: 60 * 60 * 1000,
    refetchOnWindowFocus: false,
  });

  return (
    <Card className="bg-card border-border/50 overflow-hidden">
      <CardHeader className="pb-2">
        <CardTitle className="text-sm font-semibold flex items-center gap-2 text-foreground">
          <Bot className="size-4 text-gold" />
          <span>飘叔锐评</span>
          <span className="text-muted-foreground font-normal text-xs">
            AI Daily Digest
          </span>
        </CardTitle>
      </CardHeader>
      <CardContent className="pb-4">
        {isLoading && <DigestSkeleton />}

        {isError && !data && (
          <div className="text-center py-6">
            <p className="text-bearish text-xs">Failed to load digest</p>
          </div>
        )}

        {!isLoading && data && (
          <div className="space-y-1">
            {/* Digest content */}
            <div className="max-h-72 overflow-y-auto pr-1 custom-scrollbar">
              {renderDigest(data.digest)}
            </div>

            {/* Footer: AI badge + time */}
            <div className="flex items-center justify-between pt-3 mt-2 border-t border-border/40">
              <Badge
                variant="outline"
                className="text-[10px] px-1.5 py-0 h-5 border-gold/20 text-gold/80 bg-gold/5"
              >
                <Sparkles className="size-2.5 mr-0.5" />
                Generated by AI
              </Badge>
              {data.generatedAt && (
                <span className="text-[10px] text-muted-foreground">
                  {new Date(data.generatedAt).toLocaleDateString(undefined, {
                    month: 'short',
                    day: 'numeric',
                    hour: '2-digit',
                    minute: '2-digit',
                  })}
                </span>
              )}
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
